/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: zct_33 (https://sketchfab.com/zct_33)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/emi-miniroyaleio-rigged-36e3213f8da04353be20e25ef4b6951c
Title: Emi - miniroyale.io - (Rigged)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Rnd_HAR} skeleton={nodes.Object_7.skeleton} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Rnd_HAR} skeleton={nodes.Object_9.skeleton} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Rnd_EYE} skeleton={nodes.Object_11.skeleton} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.SkinTexture} skeleton={nodes.Object_13.skeleton} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Rnd_HDS} skeleton={nodes.Object_15.skeleton} />
      <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Rnd_LGS} skeleton={nodes.Object_17.skeleton} />
      <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.Rnd_BDY} skeleton={nodes.Object_19.skeleton} />
      <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.Rnd_BDY} skeleton={nodes.Object_21.skeleton} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
