const cartItems = [
    {
        id: 1,
        shopName: 'Dripstr Official',
        title: 'Dripstr Shirt',
        description: 'This is a great product that you will love.',
        image: 'https://via.placeholder.com/150',
        price: 29.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 1.1,
        shopName: 'Dripstr Official',
        title: 'Almighty Push Shirt',
        description: 'Naruto Pain Shirt.',
        image: 'https://via.placeholder.com/150',
        price: 29.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 1.2,
        shopName: 'Dripstr Official',
        title: 'Pain Hoodie',
        description: 'Ultimate Pain Hoodie for fans.',
        image: 'https://via.placeholder.com/150',
        price: 49.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 2,
        shopName: 'Genghis Chan',
        title: '"I conquered the world" - Genghis',
        description: 'Short for "Greatness"',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 2.1,
        shopName: 'Genghis Chan',
        title: 'UwU',
        description: 'U wot m8?',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 3,
        shopName: 'Goth Boi Clique',
        title: 'Lil Peep Shirt',
        description: 'Loving you is like a fairytale.',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 3.1,
        shopName: 'Goth Boi Clique',
        title: 'Sad Boy Shirt',
        description: 'I am a sad boy.',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 3.2,
        shopName: 'Goth Boi Clique',
        title: 'Anti Social Social Clique',
        description: 'anti social.',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 3.3,
        shopName: 'Goth Boi Clique',
        title: 'Gojo Pants',
        description: 'I alone am the honored one.',
        image: 'https://via.placeholder.com/150',
        price: 29.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 4,
        shopName: 'DripAnime',
        title: 'Dandadan',
        description: 'Turbo Granny.',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 4.1,
        shopName: 'DripAnime',
        title: 'Suguru Geto Compression Shirt',
        description: 'Compression Shirt for Suguru.',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 4.2,
        shopName: 'DripAnime',
        title: 'Gun Park Glasses',
        description: 'Be like Gun Park.',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 5,
        shopName: 'Baltazar',
        title: 'Baltazar Hoodie',
        description: 'Comfortable and cozy hoodie.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 5.1,
        shopName: 'Baltazar',
        title: 'Baltazar T-shirt',
        description: 'The perfect casual T-shirt for your daily wear.',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 5.2,
        shopName: 'Baltazar',
        title: 'Baltazar Sneakers',
        description: 'Stylish and comfortable sneakers.',
        image: 'https://via.placeholder.com/150',
        price: 59.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 6,
        shopName: 'StreetVibe',
        title: 'Vibe Check Sweatshirt',
        description: 'Be a vibe on the streets.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 7,
        shopName: 'Hype Beast',
        title: 'Yeezy Inspired Shoes',
        description: 'Take your drip to the next level with these Yeezy-inspired kicks.',
        image: 'https://via.placeholder.com/150',
        price: 89.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 7.1,
        shopName: 'Hype Beast',
        title: 'Playboi Carti Hoodie',
        description: 'FWAEH!!!',
        image: 'https://via.placeholder.com/150',
        price: 89.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 7.2,
        shopName: 'Hype Beast',
        title: 'XXXTENTACION Hoodie',
        description: 'Look at me!',
        image: 'https://via.placeholder.com/150',
        price: 89.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 7.3,
        shopName: 'Hype Beast',
        title: 'Central Cee Pro Club Shirt',
        description: 'How can I be homophobic?',
        image: 'https://via.placeholder.com/150',
        price: 89.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 8,
        shopName: 'FlexGear',
        title: 'Camo Cargo Pants',
        description: 'For those who want to flex in comfort.',
        image: 'https://via.placeholder.com/150',
        price: 49.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 8.1,
        shopName: 'FlexGear',
        title: 'Drifit Long Sleeves',
        description: 'For those who want to flex in comfort.',
        image: 'https://via.placeholder.com/150',
        price: 49.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 9,
        shopName: 'Street Ink',
        title: 'Tattoo Print Hoodie',
        description: 'Show off your street art with this hoodie.',
        image: 'https://via.placeholder.com/150',
        price: 49.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 10,
        shopName: 'DripGrail',
        title: 'Grail Snapback Cap',
        description: 'The perfect snapback cap to complete your drip.',
        image: 'https://via.placeholder.com/150',
        price: 24.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 11,
        shopName: 'Vibe Nation',
        title: 'Street Kings T-shirt',
        description: 'Rule the streets in style.',
        image: 'https://via.placeholder.com/150',
        price: 22.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 11.1,
        shopName: 'Vibe Nation',
        title: 'El Chapo T-shirt',
        description: 'Rule the streets in style.',
        image: 'https://via.placeholder.com/150',
        price: 22.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 12,
        shopName: 'Hype Streetwear',
        title: 'Supreme Joggers',
        description: 'Get comfy with these sleek joggers.',
        image: 'https://via.placeholder.com/150',
        price: 49.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 12.1,
        shopName: 'Hype Streetwear',
        title: 'LV inspired Sneakers',
        description: 'Bootleg LV sneakers.',
        image: 'https://via.placeholder.com/150',
        price: 49.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },      
      {
        id: 13,
        shopName: 'Flexwear',
        title: 'Glow in the Dark Sneakers',
        description: 'Sneakers that shine bright at night.',
        image: 'https://via.placeholder.com/150',
        price: 79.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 14,
        shopName: 'Street Legends',
        title: 'Graffiti Hoodie',
        description: 'Express your street art vibe.',
        image: 'https://via.placeholder.com/150',
        price: 54.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 15,
        shopName: 'Urban Flow',
        title: 'Neon Tracksuit',
        description: 'Stay fresh and glowing with this neon tracksuit.',
        image: 'https://via.placeholder.com/150',
        price: 69.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 16,
        shopName: 'Rogue Clothing',
        title: 'Drip Squad Hoodie',
        description: 'Perfect for the squad that stays dripping.',
        image: 'https://via.placeholder.com/150',
        price: 59.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 17,
        shopName: 'Drip Society',
        title: 'Street Fighter Jacket',
        description: 'For those who fight in style.',
        image: 'https://via.placeholder.com/150',
        price: 89.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 18,
        shopName: 'Vibe City',
        title: 'Bubblegum Pink Crocs',
        description: 'The streetwear classic with a pop of color.',
        image: 'https://via.placeholder.com/150',
        price: 34.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 19,
        shopName: 'The Drip Lab',
        title: 'Panda Print Sweatpants',
        description: 'Cute and comfy for your street style.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 20,
        shopName: 'Vibe Wave',
        title: 'Skull and Roses T-shirt',
        description: 'A mix of danger and beauty.',
        image: 'https://via.placeholder.com/150',
        price: 24.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 21,
        shopName: 'Urban Legends',
        title: 'Cyber Punk Beanie',
        description: 'A stylish beanie for futuristic vibes.',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 22,
        shopName: 'Flex Culture',
        title: 'Blackout Mask',
        description: 'Keep it mysterious with this blackout mask.',
        image: 'https://via.placeholder.com/150',
        price: 14.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 23,
        shopName: 'Street Stylz',
        title: 'Camo Snapback Cap',
        description: 'Complete your outfit with this camo snapback.',
        image: 'https://via.placeholder.com/150',
        price: 24.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 24,
        shopName: 'Vibe Nation',
        title: 'Midnight Tracksuit',
        description: 'A sleek and dark tracksuit for late-night vibes.',
        image: 'https://via.placeholder.com/150',
        price: 79.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 25,
        shopName: 'Gothic Drip',
        title: 'Vampire Hoodie',
        description: 'For those who live life on the edge.',
        image: 'https://via.placeholder.com/150',
        price: 59.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 26,
        shopName: 'Street Couture',
        title: 'Luxury Tracksuit',
        description: 'A track jacket that brings out the drip.',
        image: 'https://via.placeholder.com/150',
        price: 89.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 27,
        shopName: 'Graffiti Wear',
        title: 'Tag Crewneck Sweater',
        description: 'Represent your graffiti roots.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 28,
        shopName: 'Vibe Lab',
        title: 'Street X T-shirt',
        description: 'Perfect for the streetwear aficionado.',
        image: 'https://via.placeholder.com/150',
        price: 29.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 29,
        shopName: 'Elite Drip',
        title: 'Limited Edition Drip Hoodie',
        description: 'Be exclusive with this limited edition hoodie.',
        image: 'https://via.placeholder.com/150',
        price: 89.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 30,
        shopName: 'DripCity',
        title: 'All-Black Everything T-shirt',
        description: 'Keep it simple but classy with all black.',
        image: 'https://via.placeholder.com/150',
        price: 19.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 31,
        shopName: 'Fresh Drip',
        title: 'DripWave Tracksuit',
        description: 'Surf the streets in this sleek tracksuit.',
        image: 'https://via.placeholder.com/150',
        price: 79.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 32,
        shopName: 'Vibe Lab',
        title: 'Rising Star Hoodie',
        description: 'For those who shine bright like a star.',
        image: 'https://via.placeholder.com/150',
        price: 49.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 33,
        shopName: 'Hype Legends',
        title: 'Street Royalty Shirt',
        description: 'Feel like a king on the streets.',
        image: 'https://via.placeholder.com/150',
        price: 22.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 34,
        shopName: 'Flex Nation',
        title: 'Urban Legend Cap',
        description: 'Top off your drip with this classic cap.',
        image: 'https://via.placeholder.com/150',
        price: 24.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 35,
        shopName: 'Vibe Wear',
        title: 'Skater Jacket',
        description: 'For skaters who want to stand out.',
        image: 'https://via.placeholder.com/150',
        price: 69.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 36,
        shopName: 'Fresh Wave',
        title: 'Glow Up Sneakers',
        description: 'These sneakers will have you glowing.',
        image: 'https://via.placeholder.com/150',
        price: 79.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 37,
        shopName: 'Drip Society',
        title: 'Psychedelic Hoodie',
        description: 'Turn heads with this psychedelic hoodie.',
        image: 'https://via.placeholder.com/150',
        price: 59.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 38,
        shopName: 'Urban Essentials',
        title: 'Minimalist Backpack',
        description: 'Perfect for keeping your essentials.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 39,
        shopName: 'Drip Dream',
        title: 'City Life Sweatshirt',
        description: 'For those who love the city grind.',
        image: 'https://via.placeholder.com/150',
        price: 49.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 40,
        shopName: 'Flex Flow',
        title: 'Vibe King Hat',
        description: 'Feel like royalty with this crown-like cap.',
        image: 'https://via.placeholder.com/150',
        price: 24.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 41,
        shopName: 'Vibe Vision',
        title: 'Street Kings Snapback',
        description: 'A snapback for the kings of the street.',
        image: 'https://via.placeholder.com/150',
        price: 27.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 42,
        shopName: 'Hype Streetwear',
        title: 'Laser Cut Drip Pants',
        description: 'Sleek, stylish, and futuristic.',
        image: 'https://via.placeholder.com/150',
        price: 59.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 43,
        shopName: 'Flex Legends',
        title: 'Maverick Tracksuit',
        description: 'For the bold and adventurous.',
        image: 'https://via.placeholder.com/150',
        price: 69.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 44,
        shopName: 'Vibe Nation',
        title: 'Electric Blue Hoodie',
        description: 'Brighten up your day with this electric blue hoodie.',
        image: 'https://via.placeholder.com/150',
        price: 49.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 45,
        shopName: 'Street Couture',
        title: 'Camo Cargo Shorts',
        description: 'For the street-ready summer days.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 45.1,
        shopName: 'Street Couture',
        title: 'GTA San Andreas Hoodie',
        description: 'Oh Sh*t, Here we go again.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 45.2,
        shopName: 'Street Couture',
        title: 'GTA V Shirt',
        description: 'Lamar is the best.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 45.3,
        shopName: 'Street Couture',
        title: 'GTA V Shirt',
        description: 'Franklin is the best.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 46,
        shopName: 'Fresh Vibes',
        title: 'Drip Star Socks',
        description: 'Rock these socks for that extra drip.',
        image: 'https://via.placeholder.com/150',
        price: 9.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 47,
        shopName: 'Vibe Vision',
        title: 'Tech Drip Backpack',
        description: 'Keep your gear in this tech-inspired backpack.',
        image: 'https://via.placeholder.com/150',
        price: 49.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 48,
        shopName: 'Urban Flex',
        title: 'Future Boy Sneakers',
        description: 'Sneakers made for tomorrows street style.',
        image: 'https://via.placeholder.com/150',
        price: 79.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 49,
        shopName: 'Street Legends',
        title: 'Retro Drip Jacket',
        description: 'A blast from the past with a fresh drip.',
        image: 'https://via.placeholder.com/150',
        price: 69.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 49.1,
        shopName: 'Street Legends',
        title: '2Pac Jacket',
        description: 'A blast from the past with a fresh drip.',
        image: 'https://via.placeholder.com/150',
        price: 69.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 49.2,
        shopName: 'Street Legends',
        title: 'Biggie Smalls Jacket',
        description: 'A blast from the past with a fresh drip.',
        image: 'https://via.placeholder.com/150',
        price: 69.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 49.3,
        shopName: 'Street Legends',
        title: 'Juice WRLD Hoodie',
        description: 'Lucid Dreams.',
        image: 'https://via.placeholder.com/150',
        price: 69.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 49.4,
        shopName: 'Street Legends',
        title: 'Juice WRLD Hoodie',
        description: 'All Girls Are The Same.',
        image: 'https://via.placeholder.com/150',
        price: 69.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 50,
        shopName: 'Hype Streetwear',
        title: 'Neon Green Joggers',
        description: 'Brighten up your joggers game with neon green.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 51,
        shopName: 'Hype Streetwear',
        title: 'Neon Green Joggers',
        description: 'Brighten up your joggers game with neon green.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 51.1,
        shopName: 'Hype Streetwear',
        title: 'Neon Green Joggers',
        description: 'Brighten up your joggers game with neon green.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 51.2,
        shopName: 'Hype Streetwear',
        title: 'Neon Green Joggers',
        description: 'Brighten up your joggers game with neon green.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 51.3,
        shopName: 'Hype Streetwear',
        title: 'Neon Green Joggers',
        description: 'Brighten up your joggers game with neon green.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 51.4,
        shopName: 'Hype Streetwear',
        title: 'Neon Green Joggers',
        description: 'Brighten up your joggers game with neon green.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 52,
        shopName: 'HypeVest',
        title: 'Drip Vest Bag',
        description: 'Bag for your drip.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 52.1,
        shopName: 'HypeVest',
        title: 'Cyberpunk Vest Bag',
        description: 'Like a cyberpunk ninja.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 52.2,
        shopName: 'HypeVest',
        title: 'Fanny Pack',
        description: 'Small Belongings.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 52.3,
        shopName: 'HypeVest',
        title: 'Fanny Pack',
        description: 'Small Belongings.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53,
        shopName: 'Bandripton',
        title: 'Metallica Hoodie',
        description: 'Enter the sandman.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.1,
        shopName: 'Bandripton',
        title: 'Metallica Shirt',
        description: 'Enter the sandman.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.2,
        shopName: 'Bandripton',
        title: 'Metallica Short',
        description: 'Enter the sandman.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.3,
        shopName: 'Bandripton',
        title: 'AC DC Hoodie',
        description: 'Highway To Hell.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.4,
        shopName: 'Bandripton',
        title: 'AC DC Short',
        description: 'Highway To Hell.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.5,
        shopName: 'Bandripton',
        title: 'AC DC Shirt',
        description: 'Highway To Hell.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.6,
        shopName: 'Bandripton',
        title: 'AC DC Cap',
        description: 'Highway To Hell.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.7,
        shopName: 'Bandripton',
        title: 'The Smiths Shirt',
        description: 'The Queen is Dead.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.8,
        shopName: 'Bandripton',
        title: 'The Smiths Long Sleeves',
        description: 'The Queen is Dead.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.9,
        shopName: 'Bandripton',
        title: 'The Smiths Short',
        description: 'The Queen is Dead.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.01,
        shopName: 'Bandripton',
        title: 'The Smiths Shirt',
        description: 'How Soon is Now.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 53.011,
        shopName: 'Bandripton',
        title: 'The Smiths Shirt',
        description: 'How Soon is Now.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 54,
        shopName: 'Hustler',
        title: 'Pablo Escobar Shirt',
        description: 'KingPin.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 54.1,
        shopName: 'Hustler',
        title: 'Pablo Escobar Hoodie',
        description: 'KingPin.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 54.2,
        shopName: 'Hustler',
        title: 'Pablo Escobar White Shirt',
        description: 'KingPin.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 54.3,
        shopName: 'Hustler',
        title: 'ScarFace Shirt',
        description: 'KingPin.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 54.4,
        shopName: 'Hustler',
        title: 'Andrew Tate Shirt',
        description: 'TOP G!!!',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      {
        id: 55,
        shopName: 'League of Legends',
        title: 'Arcane Powder Shirt',
        description: 'Oh the misery.',
        image: 'https://via.placeholder.com/150',
        price: 39.99,
        quantity: 1,
        shippingFee: 9.99,
        checked: false,
      },
      
];

export default cartItems;